import i18n from 'locales/i18n';
import paths, { workbenchEntryPath } from './paths';

export const templateSitemap = [
  {
    id: 'homepage',
    get subheader() {
      return i18n.t('ui.routes.sitemap.homepage_ac066591');
    },
    key: 'homepage',
    icon: 'material-symbols:data-exploration-outline-rounded',
    items: [
      {
        name: 'E-commerce',
        key: 'e_commerce',
        path: paths.ecommerce,
        pathName: 'e-commerce',
        icon: 'material-symbols:shopping-cart-outline',
        active: true,
      },
      {
        name: 'Project ',
        path: paths.project,
        key: 'project',
        pathName: 'project ',
        icon: 'material-symbols:pending-actions-rounded',
        active: true,
      },
      {
        name: 'CRM',
        key: 'crm',
        path: paths.crm,
        pathName: 'crm',
        icon: 'material-symbols:phone-in-talk-outline-rounded',
        active: true,
      },
      {
        name: 'Analytics',
        key: 'analytics',
        path: paths.analytics,
        pathName: 'analytics',
        icon: 'material-symbols:query-stats-rounded',
        active: true,
      },
      {
        name: 'HRM',
        key: 'hrm',
        path: paths.hrm,
        pathName: 'hrm',
        icon: 'material-symbols:manage-accounts-outline',
        active: true,
      },
      {
        name: 'Time Tracker',
        key: 'time-tracker',
        path: paths.timeTracker,
        pathName: 'time-tracker',
        icon: 'material-symbols:timer-outline-rounded',
        active: true,
      },
      {
        name: 'Hiring',
        key: 'hiring',
        path: paths.hiring,
        pathName: 'hiring',
        icon: 'material-symbols:work-outline',
        active: true,
      },
      {
        name: 'Employee',
        key: 'employee',
        path: paths.employee,
        pathName: 'employee',
        icon: 'material-symbols:group-outline-rounded',
        active: true,
      },
    ],
  },
  {
    id: 'apps',
    get subheader() {
      return i18n.t('ui.routes.sitemap.apps_d9a36850');
    },
    key: 'apps',
    icon: 'material-symbols:widgets-outline-rounded',
    items: [
      {
        name: 'E-commerce',
        key: 'e_commerce',
        pathName: 'ecommerce',
        icon: 'material-symbols:storefront-outline-rounded',
        active: true,
        items: [
          {
            name: 'Admin',
            key: 'admin',
            pathName: 'admin',
            active: true,
            items: [
              {
                name: 'Product listing',
                key: 'product_listing',
                path: paths.adminProductListing,
                pathName: 'product-listing',
                active: true,
              },
              {
                name: 'Product list',
                key: 'product_list',
                path: paths.adminProductList,
                pathName: 'product-list',
                active: true,
              },
              {
                name: 'Order list',
                key: 'order_list',
                path: paths.adminOrderList,
                pathName: 'order-list',
                active: true,
              },
              {
                name: 'Order',
                key: 'order',
                path: paths.adminOrder,
                pathName: 'order',
                active: true,
              },
              {
                name: 'Create order',
                key: 'create_order',
                path: paths.adminCreateOrder,
                pathName: 'create-order',
                active: true,
              },
              {
                name: 'Refund',
                key: 'refund',
                path: paths.adminRefund,
                pathName: 'refund',
                active: true,
              },
              {
                name: 'Invoice list',
                key: 'invoice_list',
                path: paths.adminInvoiceList,
                pathName: 'invoice-list',
                active: true,
              },
              {
                name: 'Invoice',
                key: 'invoice',
                path: paths.adminInvoice,
                pathName: 'invoice',
                active: true,
              },
            ],
          },
          {
            name: 'Customer',
            key: 'customer',
            pathName: 'customer',
            active: true,
            items: [
              {
                name: 'Homepage',
                key: 'homepage',
                path: paths.ecommerceHomepage,
                pathName: 'homepage',
                active: true,
              },
              {
                name: 'Products',
                key: 'products',
                path: paths.products,
                pathName: 'products',
                active: true,
              },
              {
                name: 'Product details',
                key: 'product_details',
                path: paths.productDetails(),
                pathName: 'product-details',
                active: true,
              },
              {
                name: 'Cart',
                key: 'cart',
                path: paths.cart,
                pathName: 'cart',
                active: true,
              },
              {
                name: 'Customer account',
                key: 'customer_account',
                path: paths.customerAccount,
                pathName: 'customer-account',
                active: true,
              },
              {
                name: 'Checkout',
                key: 'checkout',
                path: paths.checkout,
                pathName: 'checkout',
                active: true,
              },
              {
                name: 'Payment',
                key: 'payment',
                path: paths.payment,
                pathName: 'payment',
                active: true,
              },
              {
                name: 'Order confirmation',
                key: 'order_confirmation',
                path: paths.orderConfirmation,
                pathName: 'order-confirmation',
                active: true,
              },
              {
                name: 'Wishlist',
                key: 'wishlist',
                path: paths.wishlist,
                pathName: 'wishlist',
                active: true,
              },
              {
                name: 'Order list',
                key: 'order_list',
                path: paths.orderList,
                pathName: 'order-list',
                active: true,
              },
              {
                name: 'Order details',
                key: 'order_details',
                path: paths.orderDetails,
                pathName: 'order-details',
                active: true,
              },
              {
                name: 'Track order',
                key: 'track_order',
                path: paths.orderTrack,
                pathName: 'track-order',
                active: true,
              },
            ],
          },
        ],
      },
      {
        name: 'CRM',
        pathName: 'crm',
        key: 'crm_pages',
        icon: 'material-symbols:phone-in-talk-outline-rounded',
        active: true,
        items: [
          {
            name: 'Deals',
            key: 'deals',
            path: paths.deals,
            pathName: 'deals',
            active: true,
          },
          {
            name: 'Lead details',
            key: 'lead_details',
            path: paths.leadDetails,
            pathName: 'lead-details',
            active: true,
          },
          {
            name: 'Deal details',
            key: 'deal_details',
            path: paths.dealDetails,
            pathName: 'deal-details',
            active: true,
          },
          {
            name: 'Add contact',
            key: 'add_contact',
            path: paths.addContact,
            pathName: 'add-contact',
            active: true,
          },
        ],
      },
      {
        name: 'Project',
        pathName: 'project',
        key: 'project',
        icon: 'material-symbols:pending-actions-rounded',
        active: true,
        items: [
          {
            name: 'Project List',
            key: 'project_list',
            path: paths.projectList,
            pathName: 'project-list',
            active: true,
          },
          {
            name: 'Create Project',
            key: 'create_project',
            path: paths.createProject,
            pathName: 'create-project',
            active: true,
          },
          {
            name: 'Team Member List',
            key: 'team_member_list',
            path: paths.teamMemberList,
            pathName: 'team-member-list',
            active: true,
          },
          {
            name: 'Gantt Chart',
            key: 'gantt_chart',
            path: paths.ganttChart,
            pathName: 'gantt-chart',
            active: true,
          },
          {
            name: 'Timeline View',
            key: 'timeline_view',
            path: paths.timelineView,
            pathName: 'timeline-view',
            active: true,
          },
          {
            name: 'Automations',
            key: 'automations',
            path: paths.automationList,
            pathName: 'automations',
            active: true,
          },
          {
            name: 'Create Automation',
            key: 'create_automation',
            path: paths.createAutomation,
            pathName: 'create-automation',
            active: true,
          },
          {
            name: 'Table View',
            key: 'table_view',
            path: paths.tableView,
            pathName: 'table-view',
            active: true,
          },
        ],
      },
      {
        name: 'HRM',
        pathName: 'hrm',
        key: 'hrm',
        icon: 'material-symbols:manage-accounts-outline',
        active: true,
        items: [
          {
            name: 'Payroll',
            key: 'payroll',
            pathName: 'payroll',
            active: true,
            items: [
              {
                name: 'Payroll Overview',
                key: 'payroll_overview',
                path: paths.hrmPayrollDashboard,
                pathName: 'payroll-overview',
                active: true,
              },
              {
                name: 'Run Payroll',
                key: 'run_payroll',
                path: paths.hrmPayrollRun,
                pathName: 'run-payroll',
                active: true,
              },
              {
                name: 'Payroll Review',
                key: 'payroll_review',
                path: paths.hrmPayrollReview,
                pathName: 'payroll-review',
                active: true,
              },
            ],
          },
          {
            name: 'Performance Management',
            key: 'performance_management',
            pathName: 'performance-management',
            active: true,
            items: [
              {
                name: 'Goals',
                key: 'goals',
                path: paths.hrmPerformanceGoals,
                pathName: 'goals',
                active: true,
              },
              {
                name: 'New Goal',
                key: 'new_goal',
                path: paths.hrmPerformanceNewGoal,
                pathName: 'new-goal',
                active: true,
              },
              {
                name: 'Appraisal List',
                key: 'appraisal_list',
                path: paths.hrmPerformanceAppraisalList,
                pathName: 'appraisal-list',
                active: true,
              },
              {
                name: 'Appraisal Cycle',
                key: 'appraisal_cycle',
                path: paths.hrmPerformanceAppraisalCycle,
                pathName: 'appraisal-cycle',
                active: true,
              },
              {
                name: 'Feedback',
                key: 'feedback',
                path: paths.hrmPerformanceFeedback,
                pathName: 'feedback',
                active: true,
              },
            ],
          },
        ],
      },
      {
        name: 'Invoice',
        key: 'invoice',
        pathName: 'invoice',
        icon: 'material-symbols:receipt-long-rounded',
        active: true,
        items: [
          {
            name: 'Invoice List',
            key: 'invoice_list',
            path: paths.invoiceList,
            pathName: 'invoice-list',
            active: true,
          },
          {
            name: 'Create Invoice',
            key: 'create_invoice',
            path: paths.createInvoice,
            pathName: 'create-invoice',
            active: true,
          },
          {
            name: 'Invoice Preview',
            key: 'invoice_preview',
            path: paths.invoicePreview,
            pathName: 'invoice-preview',
            selectionPrefix: '/invoice/invoice-preview',
            active: true,
          },
        ],
      },
      {
        name: 'Email',
        pathName: 'email',
        key: 'email',
        icon: 'material-symbols:mail-outline-rounded',
        active: true,
        items: [
          {
            name: 'Inbox',
            key: 'inbox',
            path: paths.emailLabel('inbox'),
            selectionPrefix: '/email/list',
            pathName: 'email-inbox',
            active: true,
          },
          {
            name: 'Email detail',
            key: 'email_detail',
            selectionPrefix: '/email/details',
            path: paths.emailDetails('inbox', '1'),
            pathName: 'email-detail',
            active: true,
          },
        ],
      },
      {
        name: 'Events',
        key: 'events',
        pathName: 'events',
        icon: 'material-symbols:calendar-clock-outline-rounded',
        active: true,
        items: [
          {
            name: 'Create event',
            key: 'create_event',
            path: paths.createEvent,
            pathName: 'create-event',
            active: true,
          },
          {
            name: 'Event detail',
            key: 'event_detail',
            path: paths.events,
            pathName: 'event-detail',
            active: true,
          },
        ],
      },
      {
        name: 'Kanban',
        key: 'kanban',
        pathName: 'kanban',
        icon: 'material-symbols:view-kanban-outline-rounded',
        active: true,
        items: [
          {
            name: 'Kanban',
            key: 'kanban',
            path: paths.kanban,
            pathName: 'kanban',
            active: true,
          },
          {
            name: 'Boards',
            key: 'boards',
            path: paths.boards,
            pathName: 'boards',
            active: true,
          },
          {
            name: 'Create board',
            key: 'create_board',
            path: paths.createBoard,
            pathName: 'create-board',
            active: true,
          },
        ],
      },
      {
        name: 'Time Tracker',
        key: 'time-tracker',
        pathName: 'time-tracker',
        icon: 'material-symbols:timer-outline-rounded',
        active: true,
        items: [
          {
            name: 'Time Sheets',
            key: 'time_tracker_timesheet',
            path: paths.timeTrackerTimeSheets,
            pathName: 'time-sheets',
            active: true,
          },
          {
            name: 'Screenshots',
            key: 'time_tracker_screenshots',
            path: paths.timeTrackerScreenshots,
            pathName: 'screenshots',
            active: true,
          },
          {
            name: 'Apps & Sites',
            key: 'time_tracker_apps_sites',
            path: paths.timeTrackerAppsSites,
            pathName: 'apps-sites',
            active: true,
          },
          {
            name: 'Report',
            key: 'time_tracker_report',
            path: paths.timeTrackerReport,
            pathName: 'report',
            active: true,
          },
        ],
      },
      {
        name: 'Hiring',
        key: 'hiring',
        pathName: 'hiring',
        icon: 'material-symbols:work-outline',
        active: true,
        items: [
          {
            name: 'Admin',
            key: 'admin',
            pathName: 'admin',
            active: true,
            items: [
              {
                name: 'Job Opening',
                key: 'job_opening',
                path: paths.hiringJobOpening,
                pathName: 'job-opening',
                active: true,
              },
              {
                name: 'Pipeline',
                key: 'pipeline',
                path: paths.hiringPipeline,
                pathName: 'pipeline',
                active: true,
              },
              {
                name: 'New Opening',
                key: 'new_opening',
                path: paths.hiringNewOpening,
                pathName: 'new-opening',
                active: true,
              },
              {
                name: 'Candidate Details',
                key: 'candidate_details',
                path: paths.hiringCandidateDetails,
                pathName: 'candidate-details',
                active: true,
              },
            ],
          },
          {
            name: 'Candidate',
            key: 'candidate',
            pathName: 'candidate',
            active: true,
            items: [
              {
                name: 'Job List',
                key: 'job_list',
                path: paths.hiringJobList,
                pathName: 'job-list',
                active: true,
              },
              {
                name: 'Job Details',
                key: 'job_details',
                path: paths.hiringJobDetails(),
                selectionPrefix: '/hiring/candidate/job-details',
                pathName: 'job-details',
                active: true,
              },
              {
                name: 'Job Application',
                key: 'job_application',
                path: paths.hiringJobApplication,
                pathName: 'job-application',
                active: true,
              },
            ],
          },
        ],
      },
      {
        name: 'Member',
        pathName: 'member',
        key: 'member',
        icon: 'material-symbols:person-text-outline-rounded',
        active: true,
        items: [
          {
            name: 'Member List',
            key: 'member_list',
            path: paths.members,
            pathName: 'kanban',
            active: true,
          },
          {
            name: 'Profile',
            key: 'member_profile',
            path: paths.memberProfile,
            pathName: 'profile',
            active: true,
          },
          {
            name: 'New Member',
            key: 'member_new_member',
            path: paths.memberNewMember,
            pathName: 'new-member',
            active: true,
          },
        ],
      },
      {
        name: 'Content',
        key: 'content',
        pathName: 'content',
        icon: 'material-symbols:library-books-outline-rounded',
        active: true,
        items: [
          {
            name: 'Homepage',
            key: 'homepage',
            path: paths.content,
            pathName: 'content',
            active: true,
          },
          {
            name: 'Search Content',
            key: 'content_search',
            path: paths.contentSearch,
            pathName: 'content-search',
            active: true,
          },
          {
            name: 'Topics',
            key: 'content_topics',
            path: paths.contentTopics,
            pathName: 'content-topics',
            active: true,
          },
          {
            name: 'Blog Details',
            key: 'content_blog_details',
            path: paths.blogDetails('1'),
            selectionPrefix: '/content/blogs',
            pathName: 'blogs',
            active: true,
          },
          {
            name: 'Podcast Details',
            key: 'content_podcast_details',
            path: paths.podcastDetails('1'),
            selectionPrefix: '/content/podcasts',
            pathName: 'podcasts',
            active: true,
          },
          {
            name: 'Video Details',
            key: 'content_video_details',
            path: paths.videoDetails('1'),
            selectionPrefix: '/content/videos',
            pathName: 'videos',
            active: true,
          },
          {
            name: 'Create Blog',
            key: 'content_create_blog',
            path: paths.createBlog,
            pathName: 'create-blog',
            active: true,
          },
          {
            name: 'Upload Media',
            key: 'content_upload_media',
            path: paths.uploadMedia,
            pathName: 'upload-media',
            active: true,
          },
        ],
      },
      {
        name: 'Chat',
        key: 'chat',
        path: paths.chat,
        pathName: 'chat',
        selectionPrefix: '/chat',
        icon: 'material-symbols:chat-bubble-outline-rounded',
        active: true,
      },
      {
        name: 'Social',
        key: 'social',
        path: paths.social,
        pathName: 'social',
        selectionPrefix: '/social',
        icon: 'material-symbols:account-box-outline',
        active: true,
      },
      {
        name: 'File manager',
        key: 'file_manager',
        path: paths.fileManager,
        pathName: 'file-manager',
        selectionPrefix: '/file-manager',
        icon: 'material-symbols:folder-outline-rounded',
        active: true,
      },
      {
        name: 'Calendar',
        key: 'calendar',
        path: paths.calendar,
        pathName: 'calendar',
        icon: 'material-symbols:calendar-month-outline',
        active: true,
      },
      {
        name: 'Scheduler',
        key: 'scheduler',
        path: paths.scheduler,
        pathName: 'scheduler',
        icon: 'material-symbols:calendar-add-on',
        active: true,
      },
    ],
  },
];

const sitemap = [
  {
    id: 'ffax',
    subheader: 'FFA-X',
    key: 'ffax.public.footer.brand',
    icon: 'material-symbols:apps-rounded',
    items: [
      {
        get name() {
          return i18n.t('ffax.navigation.workbench');
        },
        key: 'workbench',
        path: workbenchEntryPath,
        pathName: 'workbench',
        icon: 'material-symbols:apps-rounded',
        active: true,
      },
      {
        get name() {
          return i18n.t('ffax.navigation.notifications');
        },
        key: 'notifications',
        path: paths.notifications,
        pathName: 'notifications',
        icon: 'material-symbols:notifications-outline-rounded',
        active: true,
      },
    ],
  },
];

export default sitemap;
